version: '3'
services:
  dev-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: nest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs_app
    ports:
      - "3000:3000"
    depends_on:
      - dev-db
    environment:
      DATABASE_URL: ${DATABASE_URL}
volumes:
  db-data: